=== Adriankhl/jadex/jadex-kernel-component/src/main/config/jadex-component-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Lars (RTL) -->
<xs:schema targetNamespace="http://jadex.sourceforge.net/jadex" xmlns="http://jadex.sourceforge.net/jadex" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0">
	<xs:element name="componenttype" type="componenttype">
		<xs:annotation>
			<xs:documentation>A component type specifies the interface, the structure and content of a component.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="componenttype">
		<xs:annotation>
			<xs:documentation>A component type specifies the interface, the structure and content of a component.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="startabletype">
				<xs:group ref="comptypegroup"/>
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="package" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:group name="comptypegroup">
		<xs:all>
			<xs:element name="imports" type="imports" minOccurs="0"/>
			<xs:element name="arguments" type="arguments" minOccurs="0"/>
			<xs:element name="componenttypes" type="componenttypes" minOccurs="0"/>
			<xs:element name="services" type="services" minOccurs="0"/>
			<xs:element name="properties" type="properties" minOccurs="0"/>
			<xs:element name="configurations" type="configurations" minOccurs="0"/>
			<xs:element name="extensiontypes" type="extensiontypes" minOccurs="0"/>
		</xs:all>
	</xs:group>
	<xs:complexType name="imports">
		<xs:annotation>
			<xs:documentation>
				Imports allow to add packages (e.g. java.util.*)
				and classes (e.g. java.util.Map) to the class
				lookup mechanism.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="import" type="import" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						An import allows to add a package
						(e.g. java.util.*) or a class (e.g.
						java.util.Map) to the class lookup
						mechanism.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="arguments">
		<xs:annotation>
			<xs:documentation>
				Container for argument and result
				specifications.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="argument" type="argumenttype" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						An argument represents an
						in-parameter for the component.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="result" type="argumenttype" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						An argument represents an
						out-parameter for the component.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="componenttypes">
		<xs:annotation>
			<xs:documentation>
				Container for the used component types.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="componenttype" type="subcomponenttype" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						A component type is defined by a
						logical name and an implementation
						file.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="services">
		<xs:annotation>
			<xs:documentation>Service declarations of the application type.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="providedservice" type="providedservicetype" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="requiredservice" type="requiredservicetype" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="properties">
		<xs:annotation>
			<xs:documentation>Properties for specifiying settings of the application type.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="propertytype" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="configurations">
		<xs:annotation>
			<xs:documentation>
				In the configurations section, predefined
				component configurations (i.e. component
				instances) can be defined.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="configuration" type="configuration" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						A predefined component
						configuration.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="extensiontypes">
		<xs:annotation>
			<xs:documentation>
				In this section, specifications for extensions as required
				by some specific factory component extension service (e.g.
				EnvSupport) can be placed.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:any minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="subcomponenttype">
		<xs:annotation>
			<xs:documentation>Defines a component type.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="startabletype">
				<xs:attribute name="name" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>The name of the agent type (used for referring to the agent type from other parts of the application descriptor).</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="filename" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>The implementation of the agent type. Can be a logical name (resolved using imports) or a concrete file name (e.g. to a bdi agent.xml).</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="configuration">
		<xs:annotation>
			<xs:documentation>A predefined application configuration.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="startabletype">
				<xs:group ref="configgroup"/>
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:group name="configgroup">
		<xs:all>
			<xs:element name="arguments" type="configarguments" minOccurs="0"/>
			<xs:element name="components" type="configcomponents" minOccurs="0"/>
			<xs:element name="services" type="configservices" minOccurs="0"/>
			<xs:element name="providedservices" type="configprovidedservices" minOccurs="0"/>
			<xs:element name="extensions" type="extensions" minOccurs="0"/>
		</xs:all>
	</xs:group>
	<xs:complexType name="configarguments">
		<xs:annotation>
			<xs:documentation>Container for overridden arguments.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>An argument an the instance level can be used for overriding the default value declared in the argument type.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="configcomponents">
		<xs:annotation>
			<xs:documentation>Container for component instances.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="component" type="component" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>A component instance iis used to create a defineable number of components for a declared type.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="configservices">
		<xs:sequence>
			<xs:element name="providedservice" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="serviceref">
							<xs:sequence>
								<xs:element name="implementation" type="implementation"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="requiredservice" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="serviceref">
							<xs:sequence>
								<xs:element name="binding" type="binding"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="configprovidedservices"/>
	<xs:complexType name="extensions">
		<xs:annotation>
			<xs:documentation>
				In this section, specifications for extensions as required
				by some specific factory component extension service (e.g.
				EnvSupport) can be placed.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:any minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="component">
		<xs:annotation>
			<xs:documentation>An agent instance to be created when the application is started.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="startabletype">
				<xs:sequence>
					<xs:element name="arguments" minOccurs="0">
						<xs:annotation>
							<xs:documentation>Argument values to be supplied, when creating the agent.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>A single argument value. Arguments are passed as name / value pairs, where the name is supplied as attribute while the value is given as the text content of the element.</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="requiredservices" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="binding" type="binding" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="name" type="xs:string" use="optional"/>
				<xs:attribute name="type" type="xs:string" use="required"/>
				<xs:attribute name="configuration" type="xs:string" use="optional"/>
				<xs:attribute name="number" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="argument" mixed="true">
		<xs:annotation>
			<xs:documentation>A single argument value. Arguments are passed as name / value pairs, where the name is supplied as attribute while the value is given as the text content of the element.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the argument.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="import" mixed="true">
		<xs:annotation>
			<xs:documentation>An import allows to add a package (e.g. java.util.*) or a class (e.g. java.util.Map) to the class lookup mechanism.</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:complexType name="argumenttype" mixed="true">
		<xs:annotation>
			<xs:documentation>Argument specification for a component.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="typename" type="xs:string" use="optional"/>
		<xs:attribute name="class" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="propertytype" mixed="true">
		<xs:annotation>
			<xs:documentation>A property type declaration type.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="class" type="xs:string"/>
		<xs:attribute name="language" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="providedservicetype">
		<xs:annotation>
			<xs:documentation>Defines a provided service type.</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="implementation">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="implementation">
							<xs:sequence>
								<xs:element name="binding" type="binding" minOccurs="0"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="class" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="requiredservicetype">
		<xs:annotation>
			<xs:documentation>Defines a required service type.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="binding" type="binding" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="class" type="xs:string" use="required"/>
		<xs:attribute name="multiple" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="startabletype">
		<xs:annotation>
			<xs:documentation>Base type for any startable element.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="suspend" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="master" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>A master agent ist required for the application, thus, if a master agent is killed, the application will be closed down. Default is false.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="daemon" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="autoshutdown" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="binding">
		<xs:attribute name="name" type="xs:string" use="optional"/>
		<xs:attribute name="scope" use="optional" default="application">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="local"/>
					<xs:enumeration value="component"/>
					<xs:enumeration value="application"/>
					<xs:enumeration value="platform"/>
					<xs:enumeration value="global"/>
					<xs:enumeration value="upwards"/>
					<xs:enumeration value="parent"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="componentname" type="xs:string" use="optional"/>
		<xs:attribute name="componenttype" type="xs:string" use="optional"/>
		<xs:attribute name="dynamic" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="create" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="recover" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="describabletype"/>
	<xs:complexType name="serviceref">
		<xs:attribute name="ref" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="implementation" mixed="true">
		<xs:attribute name="language" type="xs:string" use="optional"/>
		<xs:attribute name="class" type="xs:string" use="optional"/>
		<xs:attribute name="proxytype" use="optional" default="decoupled">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="decoupled"/>
					<xs:enumeration value="direct"/>
					<xs:enumeration value="raw"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== Adriankhl/jadex/jadex-platform-wfms/src/main/java/jadex/wfms/WfMS.component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	<H3>Workflow Management System</H3>

	Can be used to launch the workflow management system.<br>
-->
<componenttype xmlns="http://www.activecomponents.org/jadex-component"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.activecomponents.org/jadex-component
						http://www.activecomponents.org/jadex-component-2.0.xsd"
	name="WfMS" package="jadex.wfms">
	
	<imports>
		<import>jadex.wfms.service.*</import>
		<import>jadex.wfms.service.impl.*</import>
	</imports>

	<componenttypes>
		<componenttype filename="jadex/wfms/components/Monitoring.component.xml" name="wfms_monitoring"/>
		<componenttype filename="jadex/wfms/components/UserManagement.component.xml" name="wfms_users"/>
		<componenttype filename="jadex/wfms/components/Execution.component.xml" name="wfms_execution"/>
		<componenttype filename="jadex/wfms/components/WorkitemManagement.component.xml" name="wfms_workitems"/>
		<componenttype filename="jadex/wfms/components/Access.component.xml" name="wfms_access"/>
		<componenttype filename="jadex/wfms/client/standard/StandardClientAgent.class" name="std_client"/>
	</componenttypes>
	
	<services>
	</services>
	
	<properties>
		<property name="componentviewer.viewerclass">"jadex.wfms.WfmsViewerPanel"</property>
	</properties>
	
	<configurations>
		<configuration name="Workflow Management System (1 Standard Client)">
			<components>
				<component name="wfms_monitoring" type="wfms_monitoring"/>
				<component name="wfms_users" type="wfms_users"/>
				<component name="wfms_execution" type="wfms_execution"/>
				<component name="wfms_workitems" type="wfms_workitems"/>
				<component name="wfms_access" type="wfms_access"/>
				<component name="client" type="std_client"/>
			</components>
 		</configuration>
 		
 		<configuration name="Workflow Management System (No Clients)">
			<components>
				<component name="wfms_monitoring" type="wfms_monitoring"/>
				<component name="wfms_users" type="wfms_users"/>
				<component name="wfms_execution" type="wfms_execution"/>
				<component name="wfms_workitems" type="wfms_workitems"/>
				<component name="wfms_access" type="wfms_access"/>
			</components>
 		</configuration>
	</configurations>

</componenttype>

=== Adriankhl/jadex/jadex-applications-webservice/src/main/java/jadex/webservice/examples/ws/banking/Banking.component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	<H3>Banking agent that offers a banking service.</H3>

    This example shows how a Jadex service can be automatically published
    as web service with a synchronous interfaces.
    
    The @Publish annotation requires the publishing type (e.g. web service),
    the id (e.g. a web service url) and the service type, i.e. interface to
    be specified.
-->
<componenttype xmlns="http://jadex.sourceforge.net/jadex"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jadex.sourceforge.net/jadex
						http://jadex.sourceforge.net/jadex-component-2.0.xsd"
	name="Banking" package="jadex.webservice.examples.ws.banking">
	
	<imports>
		<import>jadex.extension.ws.publish.*</import>
		<import>jadex.webservice.examples.ws.offerquote.gen.*</import>
	</imports>
	
	<services>
		<providedservice class="IBankingService">
			<implementation class="BankingService"/>
			<publish publishtype="ws" publishid="http://localhost:8080/banking" mapping="IWSBankingService"/>
		</providedservice>
	</services>
</componenttype>

=== Adriankhl/jadex/jadex-kernel-application/src/main/java/jadex/application/KernelApplication.component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Application kernel.
-->
<componenttype xmlns="http://jadex.sourceforge.net/jadex-component"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jadex.sourceforge.net/jadex-component
						http://jadex.sourceforge.net/jadex-component-2.0.xsd"
	name="KernelApplication" package="jadex.application">
	
	<imports>
		<import>jadex.commons.*</import>
		<import>jadex.bridge.*</import>
		<import>jadex.application.space.envsupport.*</import>
		<import>jadex.application.space.agr.*</import>
		<import>java.util.*</import>
	</imports>
	
	<properties>
		<property name="kernel.types" class="String[]">
			new String[]{"application.xml"}
		</property>
	</properties>
	
	<services>
		<providedservice class="IComponentFactory">
			<implementation proxytype="raw">
				new ApplicationComponentFactory(
					new Set[]
					{
						MEnvSpaceType.getXMLMapping(),
						MAGRSpaceType.getXMLMapping()
					}, 
					$component.getServiceProvider()
				)	
			</implementation>
		</providedservice>
	</services>
</componenttype>

=== Adriankhl/jadex/jadex-applications-micro/src/main/java/jadex/micro/testcases/semiautomatic/compositeservice/Calculate2.component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	<H3></H3>
-->
<componenttype xmlns="http://jadex.sourceforge.net/jadex-component"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jadex.sourceforge.net/jadex-component
						http://jadex.sourceforge.net/jadex-component-2.0.xsd"
	name="Calculate2" package="jadex.micro.testcases.semiautomatic.compositeservice">
	
	<imports>
		<import>jadex.commons.service.clock.IClockService</import>
		<import>jadex.commons.service.SServiceProvider</import>
		<import>jadex.commons.future.*</import>
	</imports>
	
	<componenttypes>
		<componenttype name="Calculator" filename="jadex/micro/examples/compositeservice/CalculatorAgent2.class" master="true"/>
		<componenttype name="Adder" filename="jadex/micro/examples/compositeservice/Adder.component.xml"/>
		<componenttype name="Subtractor" filename="jadex/micro/examples/compositeservice/Subtractor.component.xml"/>
	</componenttypes>
	
	<applications>
		<application name="User Agent">
			<components>
				<component type="Calculator" name="EmptyCalculator">
					<!-- <requiredservices>
						<requiredservice name="addservice" componentname="Adder"/>			
						<requiredservice name="subservice" componentname="Subtractor"/>			
					</requiredservices> -->
				</component>
				<component type="Adder" name="Adder"/>
				<component type="Subtractor" name="Subtractor"/>
			</components>
		</application>
	</applications>
	
</componenttype>

=== Adriankhl/jadex/jadex-platform-wfms/src/main/java/jadex/wfms/components/Execution.component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  WfMS Execution Component.
-->
<componenttype xmlns="http://jadex.sourceforge.net/jadex"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jadex.sourceforge.net/jadex
						http://jadex.sourceforge.net/jadex-component-2.0.xsd"
	name="Execution" package="jadex.wfms.components">
	
	<imports>
		<import>jadex.wfms.service.IExecutionService</import>
		<import>jadex.wfms.service.IModelRepositoryService</import>
		<import>jadex.wfms.service.IAAAService</import>
		<import>jadex.bridge.service.types.library.ILibraryService</import>
		<import>jadex.bridge.service.types.cms.IComponentManagementService</import>
	</imports>
	
	<services>
		<providedservice name="execution_service" class="IExecutionService">
			<implementation>
				new jadex.wfms.service.impl.ExecutionService()
			</implementation>
		</providedservice>
		<providedservice name="repository_service" class="IModelRepositoryService">
			<implementation>
				new jadex.wfms.service.impl.LinkedModelRepositoryService()
			</implementation>
		</providedservice>
		
		<requiredservice name="aaa_service" class="IAAAService">
			<binding recover="true" scope="global" />
		</requiredservice>
		<requiredservice name="execution_services" class="IExecutionService" multiple="true">
			<binding scope="global" dynamic="true" />
		</requiredservice>
		
		<requiredservice name="libservice" class="ILibraryService">
			<binding scope="platform" />
		</requiredservice>
		<requiredservice name="cms" class="IComponentManagementService">
			<binding scope="platform" />
		</requiredservice>
	</services>
	
</componenttype>
