=== Adriankhl/jadex/jadex-kernel-application/src/main/config/jadex-application-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by hans (kill) -->
<xs:schema targetNamespace="http://jadex.sourceforge.net/jadex-application" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://jadex.sourceforge.net/jadex-application" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0">
	<xs:element name="applicationtype">
		<xs:annotation>
			<xs:documentation>An application type specifies the structure and content of a agent application.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="applicationtype"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="applicationtype">
		<xs:annotation>
			<xs:documentation>An application type specifies the structure and content of a agent application.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="imports" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Imports allow to add packages (e.g. java.util.*) and classes (e.g. java.util.Map) to the class lookup mechanism.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="import" type="import" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>An import allows to add a package (e.g. java.util.*) or a class (e.g. java.util.Map) to the class lookup mechanism.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="arguments" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="argument" type="argumenttype" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="result" type="argumenttype" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="spacetypes" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Space types define concrete substructures of the application context, e.g. a 2D environment space or an agent-group-role based organization space. The elements of space types are defined by external XML schemas.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:any minOccurs="0" maxOccurs="unbounded"/>
						<!-- <xs:element name="spacetype" type="spacetype" minOccurs="0" maxOccurs="unbounded"/> -->
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="componenttypes" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="componenttype" type="componenttype" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="applications" minOccurs="0">
				<xs:annotation>
					<xs:documentation>In the applications section, predefined application configurations (i.e. application instances) can be defined.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="application" type="application" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>A predefined application configuration.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the application type is used as a default name for creating application instances and should correspond to the file name (without application.xml).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="package" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The package of the application type. The package should correspond to the directory structure, the application descriptor is contained in (like the package of a Java class). The package is also used for lookup of classes and other files (e.g. agent descriptors).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="componenttype">
		<xs:annotation>
			<xs:documentation>Defines an agent type.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the agent type (used for referring to the agent type from other parts of the application descriptor).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="filename" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The implementation of the agent type. Can be a logical name (resolved using imports) or a concrete file name (e.g. to a bdi agent.xml).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="application">
		<xs:annotation>
			<xs:documentation>A predefined application configuration.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="spaces" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The spaces that should available in the application context. These are space instances (or space configurations) usually referring to some defined space type. The details of a space specification are handled in separate XML schemas (e.g. for an AGR space or an evnironment space).</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:any minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="components" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="component" type="component" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the application.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="component">
		<xs:annotation>
			<xs:documentation>An agent instance to be created when the application is started.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="arguments" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Argument values to be supplied, when creating the agent.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence minOccurs="0">
						<xs:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>A single argument value. Arguments are passed as name / value pairs, where the name is supplied as attribute while the value is given as the text content of the element.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The name for the agent instance (if omitted, a name will be generated).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The type of agent to be created (as specified in the agenttypes section).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="configuration" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The configuration of the agent (as specified in the agent's ADF).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="start" type="xs:boolean" use="optional" default="true">
			<xs:annotation>
				<xs:documentation>Per default, each created agent is also started (i.e. will immidiately start to execute any actions). Set the start flag to false, if the agent should be started later manually.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="number" type="xs:int" use="optional" default="1">
			<xs:annotation>
				<xs:documentation>Allows the create multiple agent instances at once. If omitted only one agent is created.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="master" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>A master agent ist required for the application, thus, if a master agent is killed, the application will be closed down. Default is false.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="suspend" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="argument" mixed="true">
		<xs:annotation>
			<xs:documentation>A single argument value. Arguments are passed as name / value pairs, where the name is supplied as attribute while the value is given as the text content of the element.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of the argument.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="import" mixed="true">
		<xs:annotation>
			<xs:documentation>An import allows to add a package (e.g. java.util.*) or a class (e.g. java.util.Map) to the class lookup mechanism.</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:complexType name="argumenttype" mixed="true">
		<xs:annotation>
			<xs:documentation>Argument specification for a component.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="typename" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:schema>

=== Adriankhl/jadex/sodekovs-coordination/src/main/java/deco4mas/examples/iograph/IOGraph.application.xml
<!--
	<H3>Test application for the IOGraph based coordination</H3>
	
	In this example coordination information are passed over a given IOGraph.
	In the IOGraph it is specified to which agents coordination events observed in a specified agent should be passed.
-->

<applicationtype xmlns="http://jadex.sourceforge.net/jadex"
	xmlns:env="http://jadex.sourceforge.net/jadex-envspace"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jadex.sourceforge.net/jadex-application 
	                    http://jadex.sourceforge.net/jadex-application-2.0.xsd	                    
	                    http://jadex.sourceforge.net/jadex-envspace 
	                    http://jadex.sourceforge.net/jadex-envspace-2.0.xsd"
	name="IOGraph" package="deco4mas.examples.iograph">	

	<imports>
		<import>jadex.extension.envsupport.environment.space2d.*</import>
		<import>jadex.extension.envsupport.environment.*</import>
		<import>jadex.extension.envsupport.math.*</import>
		<import>jadex.extension.envsupport.dataview.*</import>
		<import>jadex.extension.envsupport.observer.perspective.*</import>
		<import>jadex.bdi.planlib.*</import>
		<import>jadex.bridge.service.*</import>
		<import>jadex.commons.future.*</import>
		<import>deco4mas.coordinate.interpreter.coordination_information.*</import>
		<import>deco4mas.coordinate.environment.*</import>
		<import>deco4mas.annotation.agent.*</import>
		<import>deco4mas.coordinate.*</import>
		<import>deco4mas.examples.iograph.*</import>
	</imports>	

			
	<extensiontypes>
		<env:envspacetype name="coordspace" width="11" height="11" class="CoordinationSpace">		
			<env:property name="dynamics_configuration">"sodekovs-coordination/src/main/java/deco4mas/examples/iograph/iograph.dynamics.xml"</env:property>

			<env:spaceexecutor class="DeltaTimeExecutor">
				<env:property name="space">$space</env:property>
				<env:property name="tick">true</env:property>
			</env:spaceexecutor>
		</env:envspacetype>
	</extensiontypes>
	
	<componenttypes>
		<componenttype name="Graph" filename="deco4mas/examples/iograph/GraphAgent.class" />
		<componenttype name="BDIGraph" filename="deco4mas/examples/iograph/BDIGraph.agent.xml" />
	</componenttypes>


	<applications>
	
	<application name="IOGraphTest">
			<extensions>	
				<env:envspace name="mycoordspace" type="coordspace" width="2" height ="2" />
			</extensions>
			<components>
				<component type="Graph">
					<arguments>
						<argument name="graphId">"1"</argument>
					</arguments>
				</component>
				<component type="Graph">
					<arguments>
						<argument name="graphId">"2"</argument>
					</arguments>
				</component>
				<component type="BDIGraph">
					<arguments>
						<argument name="graphId">"3"</argument>
					</arguments>
				</component>
				<component type="Graph">
					<arguments>
						<argument name="graphId">"4"</argument>
					</arguments>
				</component>
			</components>
 		</application>
	</applications>
	
</applicationtype>

=== Adriankhl/jadex/sodekovs-productionline/src/main/java/haw/mmlab/production_line/ProductionLine.application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	<H3>Production line scenario application descriptor</H3>
-->
<applicationtype xmlns="http://jadex.sourceforge.net/jadex"
	xmlns:env="http://jadex.sourceforge.net/jadex-envspace"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jadex.sourceforge.net/jadex-application 
	                    http://jadex.sourceforge.net/jadex-application-2.0.xsd	                    
	                    http://jadex.sourceforge.net/jadex-envspace 
	                    http://jadex.sourceforge.net/jadex-envspace-2.0.xsd"
	name="ProductionLine" package="haw.mmlab.production_line">
	
	<imports>
		<import>jadex.extension.envsupport.environment.space2d.*</import>
		<import>jadex.extension.envsupport.environment.*</import>
		<import>jadex.extension.envsupport.math.*</import>
		<import>jadex.extension.envsupport.dataview.*</import>
		<import>jadex.extension.envsupport.observer.perspective.*</import>
		<import>jadex.bdi.planlib.*</import>
		<import>jadex.bridge.service.*</import>
		<import>jadex.commons.future.*</import>
		<import>deco4mas.coordinate.interpreter.coordination_information.*</import>
		<import>deco4mas.coordinate.environment.*</import>
		<import>deco4mas.annotation.agent.*</import>
		<import>deco4mas.coordinate.*</import>
		<import>haw.mmlab.production_line.manager.*</import>
		<import>haw.mmlab.production_line.robot.*</import>
		<import>haw.mmlab.production_line.transport.*</import>
		<import>haw.mmlab.production_line.timelord.*</import>
		<import>haw.mmlab.production_line.service.*</import>
	</imports>
	
	<extensiontypes>
		<env:envspacetype name="coordspace" width="11" height="11" class="CoordinationSpace">		
			<env:property name="dynamics_configuration">"src/main/java/haw/mmlab/production_line/coordination.dynamics.xml"</env:property>

			<env:spaceexecutor class="DeltaTimeExecutor">
				<env:property name="space">$space</env:property>
				<env:property name="tick">true</env:property>
			</env:spaceexecutor>
			
		</env:envspacetype>
	</extensiontypes>
	
	<componenttypes>
		<componenttype name="Manager" filename="haw/mmlab/production_line/manager/ManagerAgent.class"/>
		<componenttype name="Transport" filename="haw/mmlab/production_line/transport/TransportAgent.class"/>
		<componenttype name="Robot" filename="haw/mmlab/production_line/robot/RobotAgent.class"/>
		<componenttype name="Timelord" filename="haw/mmlab/production_line/timelord/TimelordAgent.class"/>
		<componenttype name="Dropout" filename="haw/mmlab/production_line/dropout/DropoutAgent.class"/>
	</componenttypes>
	
	<applications>
		<application name="Default">
			<extensions>	
				<env:envspace name="mycoordspace" type="coordspace" width="2" height ="2" />
			</extensions>		
			<components>
				<component type="Manager">
					<arguments>
						<argument name="configuration_model">"conf/generated.conf.xml"</argument>
						<argument name="dropout_configuration_model">"conf/dropout.conf.xml"</argument>
						<argument name="strategy">"hybridStrategy"</argument>
					</arguments>
				</component>
			</components>
 		</application>
	</applications>
</applicationtype>
